receptsite/myauth/urls.py
from django.contrib.auth.views import LoginView
from django.urls import path

from myauth.views import login_view, logout_view, MyLogoutView, AboutMeView, RegisterView

app_name = "myauth"
urlpatterns = [
    # path('login/',
    #      LoginView.as_view(template_name="myauth:login.html", redirect_authenticated_user=True),
    #      name="login"),
        path('login/',login_view, name="login"),
        path('logout/', logout_view, name="logout"),
    #     path('logout/', MyLogoutView.as_view(), name="logout"),
        path('about-me/', AboutMeView.as_view(), name="about_me"),
        path('register/', RegisterView.as_view(), name="register"),
        ]

receptsite/recept/urls.py
from django.urls import path

from recept.views import (recept_index,
                          groups_list,
                          recept_list,
                          create_recept_user,
                          ReceptDetailsView,
                          ReceptUpdateView,
                          ReceptDeleteView)

app_name = "recept"
urlpatterns = [
    path("", recept_index, name="index"),
    path('groups/', groups_list, name="groups_list"),
    path('recepts/', recept_list, name="recept_list"),
    path('recepts/create/', create_recept_user, name="create_recept_user"),
    path('recepts/<int:pk>/', ReceptDetailsView.as_view(), name="recept_details"),
    path('recepts/<int:pk>/update/', ReceptUpdateView.as_view(), name="recept_update"),
    path('recepts/<int:pk>/delete/', ReceptDeleteView.as_view(), name="recept_delete"),

]

receptsite/receptsite/urls.py
from django.conf import settings

from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('recept/', include('recept.urls')),
    path('myauth/', include('myauth.urls')),
]
if settings.DEBUG:
    urlpatterns.extend(
        static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    )
    urlpatterns.extend(static(settings.STATIC_URL, document_root=settings.STATIC_ROOT))

receptsite/myauth/models.py
from django.db import models

# Create your models here.

receptsite/recept/models.py
from django.contrib.auth.models import User
from django.db import models

# Create your models here.
def recept_preview_directory_path(instance: "Recept", filename: str) -> str:
    return "recepts/recepts_{pk}/preview/{filename}".format(
        pk=instance.pk,
        filename=filename
    )
class Recept(models.Model):
    name = models.CharField(max_length=50)
    count_ingredients = models.CharField(max_length=3, blank=True)
    ingredients = models.TextField(null=False, blank=True)
    weight_ingredients_gramm = models.TextField(null=False, blank=True)
    author = models.TextField() #User
    preview = models.ImageField(null=True, blank=True, upload_to=recept_preview_directory_path)
    def __str__(self):
        return f"Recept(pk={self.pk}, name={self.name!r})"

receptsite/recept/forms.py
from django import forms
from django.contrib.auth.models import User

from recept.models import recept_preview_directory_path


class ReceptForm(forms.Form):
    name = forms.CharField(max_length=50)
    count_ingredients = forms.CharField(max_length=3)
    ingredients = forms.CharField(widget=forms.Textarea)
    weight_ingredients_gramm = forms.CharField(widget=forms.Textarea)
    author = forms.CharField(max_length=50)  # User
    preview = forms.ImageField()

receptsite/myauth/views.py
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User, Group
from django.contrib.auth.views import LogoutView
from django.http import HttpRequest
from django.shortcuts import render,redirect
from django.urls import reverse, reverse_lazy
from django.views.generic import TemplateView, CreateView


# Create your views here.
class AboutMeView(TemplateView):
    template_name = "myauth/about-me.html"
class RegisterView(CreateView):
    form_class = UserCreationForm
    template_name = "myauth/register.html"
    success_url = reverse_lazy("myauth:about_me")
#     log:sam
#     pas:zzxxccvv11Z

    # user = User.objects.exclude(pk=1)
    # group, created = Group.objects.get_or_create(name='user_group')
    # user.groups.add(group)
    # user.save()
    # group.save()



def login_view(request: HttpRequest):
    if request.method == "GET":
        if request.user.is_authenticated:
            return redirect('/admin/')
        return render(request, 'myauth/login.html')
    username = request.POST["username"]
    password = request.POST["password"]
    user = authenticate(request, username=username, password=password)
    if user is not None:
        login(request, user)
        return redirect("/admin/")
    return render(request, "myauth/login.html", {"error":"Ошибка авторизации"})
def logout_view(request: HttpRequest):
    logout(request)
    return redirect(reverse("myauth:login"))
class MyLogoutView(LogoutView):
    next_page = reverse_lazy("myauth:login")

receptsite/recept/views.py
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.models import Group
from django.http import HttpRequest, HttpResponse
from django.shortcuts import render, redirect, reverse
from django.urls import reverse_lazy
from django.views import View
from django.views.generic import UpdateView, DeleteView
from django.contrib.auth.mixins import LoginRequiredMixin
from recept.forms import ReceptForm
from recept.models import Recept



# Create your views here.

def recept_index(request: HttpRequest) -> HttpResponse:
    return render(request,'recept/recept-index.html')
def groups_list(request: HttpRequest) -> HttpResponse:
    context = {
        "groups": Group.objects.all(),
    }
    return render(request, 'recept/groups-list.html', context=context)

def recept_list(request: HttpRequest) -> HttpResponse:
    context = {
    "recepts": Recept.objects.all(),
    }
    return render(request, 'recept/recept-list.html', context=context)
@login_required
def create_recept_user(request: HttpRequest) -> HttpResponse:
    if request.method == "POST":
        form = ReceptForm(request.POST)
        if form.is_valid():
            Recept.objects.create(**form.cleaned_data)
            # url = reverse("recept:create_recept_user")
            # return redirect(url)

    else:
        form = ReceptForm() # or this block Recept.objects.create(**form.cleaned_data)
    context = {
            "form": form,
        }
    return render(request, "recept/create-user-recept.html", context=context)
class ReceptDetailsView(LoginRequiredMixin, View):
    def get(self, request: HttpRequest, pk:int):
        receptfind = Recept.objects.get(pk=pk)
        context = {
            "receptfind": receptfind,
        }
        return render(request,'recept/recept-details.html', context=context)
class ReceptUpdateView(LoginRequiredMixin, UpdateView):
    model = Recept
    fields = "name", "count_ingredients", "ingredients", "weight_ingredients_gramm", "author", "preview"
    template_name_suffix = "-update-form"
    def get_success_url(self):
        return reverse(
            "recept:recept_details",
            kwargs={
                "pk": self.object.pk
                    },
        )
class ReceptDeleteView(LoginRequiredMixin, DeleteView):
    model = Recept
    success_url = reverse_lazy("recept:recept_list")

receptsite/myauth/templates/myauth/about-me.html
{% extends 'myauth/base.html' %}

{% block title %}
    Обо мне
{% endblock %}

{% block body %}
<h1>Информация о пользователе</h1>
    {% if user.is_authenticated %}
      <h2>Детали</h2>
      <p>Имя {{ user.username }}</p>
      <p>Фамилия{{ user.first_name }}</p>
      <p>Отчество{{ user.last_name }}</p>
      <p>Почта{{ user.email }}</p>
    {% else %}
      <h2>Анонимный пользователь</h2>
    {% endif %}
{% endblock %}

receptsite/myauth/templates/myauth/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>
        {% block title %}
            Base title
        {% endblock %}
    </title>
</head>
<body>
    {% block body %}
            Base body
    {% endblock %}
</body>
</html>

receptsite/myauth/templates/myauth/login.html
{% extends 'myauth/base.html' %}

{% block title %}
    Авторизация
{% endblock %}

{% block body %}
    <form method="post">
        {% csrf_token %}
        {% if error %}
        <p style="color: red">
            {{ error }}
        </p>
        {% endif %}
        <p>
            <label for="username">Имя:</label>
            <input type="text" id="username" name="username" required>
        </p>
        <p>
            <label for="password">Пароль:</label>
            <input type="password" id="password" name="password" required>
        </p>
        <button type="submit">
            Войти
        </button>
    </form>

{% endblock %}

receptsite/myauth/templates/myauth/register.html
{% extends 'myauth/base.html' %}

{% block title %}
    Регистрация
{% endblock %}

{% block body %}
    <h1>Регистрация</h1>
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="Register">
    </form>
{% endblock %}

receptsite/recept/templates/recept/create-user-recept.html
{% extends 'recept/base.html' %}

{% block title %}
    Создать рецепт для пользователя
{% endblock %}

{% block body %}
<!--    {% if request.user.is_authenticated %}-->
        <h1>Создать новый рецепт для пользователя:</h1>
        <div>
        <form method="post" enctype="multipart/form-data">
            {% csrf_token %}
            {{ form.as_p }}
            <button type="submit">
                Create
            </button>
        </form>
        </div>
<!--    {% endif %}-->
{% endblock %}

receptsite/recept/templates/recept/delete-recept.html
{% extends 'recept/base.html' %}

{% block title %}
    Удаление
{% endblock %}

{% block body %}
    <h1>Вы уверены что хотите удалить?{{ object.name }}:</h1>
    <br>
    <div><a href="{% url 'recept:recept_details' pk=object.pk %}">Назад к рецепту</a> #or percept.pk
    </div>
    <br>
    <div>
        <form method="post">
            {% csrf_token %}
            {{ form.as_p }}
            <button type="submit">Удалить</button>
        </form>
    </div>
{% endblock %}

receptsite/recept/templates/recept/groups-list.html
{% extends 'recept/base.html' %}

{% block title %}
    Group List
{% endblock %}

{% block body %}
    <h1>Groups:</h1>
    <div>
      {{ groups }}
    </div>
{% endblock %}

receptsite/recept/templates/recept/recept-details.html
{% extends 'recept/base.html' %}

{% block title %}
    Рецепт #{{ recept.pk }}
{% endblock %}

{% block body %}
    <h1>Рецепт <strong>{{ recept.name }}</strong></h1>
    <div>
        <div>Название: {{ recept.name }} </div>
        <div>Количество ингридиентов: {{ recept.count_ingredients }} </div>
        <div>Ингридиенты: {{ recept.ingredients }} </div>
        <div>Вес ингридиентов: {{ recept.weight_ingredients_gramm }} </div>
        <div>Автор: {{ recept.author }}</div>
        {% if recept.preview %}
            <img src="{{ recept.preview.url }}" alt="{{ recept.preview.name }}">
        {% endif %}
    </div>
    <div><a href="{% url 'recept:recept_update' pk=recept.pk %}">Обновить рецепт</a></div>
    <div><a href="{% url 'recept:recept_delete' pk=recept.pk %}">Удалить рецепт</a></div>
{% endblock %}

receptsite/recept/templates/recept/recept-index.html
{% extends 'recept/base.html' %}

{% block title %}
    Recept
{% endblock %}

{% block body %}
    <h1>Рецепты</h1>
{% endblock %}

receptsite/recept/templates/recept/recept-list.html
{% extends 'recept/base.html' %}

{% block title %}
    Recept List
{% endblock %}

{% block body %}
    <h1>Рецепты:</h1>
    {% if recepts %}
        <div>
            {% for recept in recepts %}
                <div>
                    <p><a href="{% url 'recept:recept_details' pk=recept.pk %}">Название: {{ recept.name }}</a></p>
                    <p>Количество ингридиентов: {{ recept.count_ingredients }} </p>
                    <p>Ингридиенты: {{ recept.ingredients }} </p>
                    <p>Вес ингридиентов: {{ recept.weight_ingredients_gramm }} </p>
<!--                    <p><img src="../img/product-showcase-background_597316-255.avif" alt="image" width="360"></p>-->
                {% if recept.preview %} 
                    <img src="{{ recept.preview.url }}" alt="{{ recept.preview.name }}">
                    {% endif %}
                </div>
            {% endfor %}
        </div>
    {% else %}
    <h3>Нет рецептов</h3>
    {% endif %}
{% endblock %}

receptsite/recept/templates/recept/recept-update-form.html
{% extends 'recept/base.html' %}

{% block title %}
    Обновить рецепт
{% endblock %}

{% block body %}
    <h1>Обновить рецепт:</h1>
    <div>
      <form method="post" enctype="multipart/form-data">
          {% csrf_token %}
          {{ form.as_p }}
          <button type="submit">
              Обновить
          </button>
      </form>
    </div>
{% endblock %}